language: node_js
node_js: "node"

# Do not trigger builds on tags
if: tag IS blank

# By default, Travis CI will run a matrix of jobs
# in the 'test' stage using defaults:
# install: npm install
# script: npm run test

stages:
  - test
  - name: deploy
    if: branch = master

# Configuring Travis CI environment to be able to run
# TestCafe tests in a headless browser
# Source: https://devexpress.github.io/testcafe/documentation/continuous-integration/travis.html

before_install:
  - stty cols 80

dist: trusty
sudo: required

addons:
  firefox: latest
  apt:
    sources:
     - google-chrome
    packages:
     - google-chrome-stable fluxbox

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - fluxbox >/dev/null 2>&1 &

# Deployment using semantic-release

jobs:
  include:
    # Deploy stage will only execute on master branch (see above)
    - stage: deploy
      install: skip
      script: npx semantic-release
      after_script: skip
